### ISSUE TITLE
Compatibilité avec les headers créés sous emacs

### ISSUE THREAD

**Issue by WSoS** [matthieukern/atom-epitech-headers#2]
Si on crée le header sous emacs, il n'est pas update lorsqu'on modifie le fichier sous atom.

atom 0.196.0

**Comment by m4tm4t** [comment]
Je ne sais pas si c'est lié, mais je suis à l'ETNA et on utilise la norme epitech. 
Mon mail étant @etna-alternance.net j'ai du modifier cette ligne en remplacant `epitech.eu` par `.*`

https://github.com/matthieukern/atom-epitech-headers/blob/master/lib/epitech-headers.coffee#L88

**Comment by matthieukern** [comment]
@foohey J'ai réglé ton problème, par contre @WSoS j'arrive pas reproduire…
